### ISSUE TITLE
Running codegen.py for a CasADi MXFunction

### ISSUE THREAD

**Issue by CheeGY** [se-hwan/cusadi#1]
Hi! 

Thanks for this awesome development!

I'm running a test with a casadi function and I met the following runtime error, when I tried to run: `python run_codegen.py --fn=func`. This is when the file `cusadi/src/generateCUDACode.py` asks for `f.instruction_constant(i)` in line 91:

`RuntimeError: Error in Function::instruction_constant for 'func' [MXFunction] at .../casadi/core/function.cpp:1722:
.../casadi/core/function_internal.cpp:3269: 'instruction_constant' not defined for MXFunction`

Has anyone encountered something similar? Are there any ways to work around it?

**Comment by se-hwan** [comment]
Hi - you'll want to call `expand()` on your MX function before you vectorize it (if your casadi function is `fn_MX`, `fn_SX = fn_MX.expand()`, and then make it a function and save.
RIght now, we only parallelize SX expressions from CasADi (this is faster for evaluation, but the compiled libraries are larger compared to MX).
Some details about the differences between SX and MX can be found here: https://web.casadi.org/docs/#the-mx-symbolics

For the future, we could try parallelizing MX operations too with calls to cuBLAS and cuSPARSE, but I don't believe we can call these libraries directly from the kernel anymore as of CUDA 10.0+ :(
We would have to rethink how we did our codegen. 

One last thing - there are a few matrix operations that are not supported for `expand()`. These are the `logm` and `expm` expressions, which may come up if you are using so(3) representations for orientation. In this case, I would recommend approximating the mapping with a Taylor expansion or adding small offsets. 

Hope this answers everything! Please reopen the issue if you still run into problems.
